   [theme]
   base = "light"
   primaryColor = "#2a78d6"
   backgroundColor = "#fcfcfb"
   secondaryBackgroundColor = "#f3f5f8"
   textColor = "#0b0b0b"

   [server]
   maxUploadSize = 2000

   [browser]
   gatherUsageStats = false
